driver:
  name: podman

platforms:
  - name: instance
    image: "python-podman-systemd:latest"
    buildargs:
      BASE_IMAGE: "docker.io/library/python:3.11-slim"
    pre_build_image: false
    build:
      path: Dockerfile.j2
    # privileged: true # Removed for rootless
    # For systemd in container
    command: "/lib/systemd/systemd"
    tmpfs:
      /run: rw
      /tmp: rw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      roles_path: "../../.."
      remote_tmp: /tmp/.ansible
  inventory:
    group_vars:
      all:
        ansible_user: testops # Changed to non-root user
        ansible_become: false
        ansible_python_interpreter: /usr/local/bin/python3 # Adjusted path for new image
        

dependency:
  name: galaxy
  enabled: false

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
